### ISSUE TITLE
Create Interface for the Web-Application

### ISSUE THREAD

**Issue by AditiKhandelia** [CS455-Assignment-1/StackNServe#3]
```
As a Developer
I want the interface of the game for the web-application
for ease of visualisation and event-response.
```

**Comment by whizdor** [comment]
Resolved. Interface design can be found at https://www.canva.com/design/DAGNPAtcjYQ/WI_57OYJ3qqM8Mc39acChw/edit?utm_content=DAGNPAtcjYQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
